name: Build Linux

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      VERSION: ${{ inputs.release-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: "recursive"
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"
          cache: true
      - name: Install nuget package dependencies
        run: dotnet restore --locked-mode
      - name: Download FFmpeg Binaries
        run: python scripts/build.py -dlffmpeg
      - name: Run build script
        run: sh scripts/build-linux-x64.sh $VERSION y
      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload $VERSION build/linux-x64.tar.gz
