name: Build Linux

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: "recursive"
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          cache: true
          cache-dependency-path: src/CyberPlayer.Player/packages.lock.json
      - name: Install nuget package dependencies
        run: dotnet restore --locked-mode
