name: Dev Pre-Release

on:
  push:
    branches:
      - dev

jobs:
  call-base-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: ./.github/workflows/base-release.yml
    with:
      release-type: dev-pre-release
